### ISSUE TITLE
Installed nvim-treesitter, but after installing printf, the C file is not highlighted

### ISSUE THREAD

**Issue by IC0hO** [sainnhe/sonokai#101]
![image](https://github.com/sainnhe/sonokai/assets/43652659/b5813354-d655-417b-9e23-e1a266280731)
nvim-treesitter I installed the two parsers, C and printf. After printf is installed, the parameters should be highlighted, but this color scheme does not.

Here is another color scheme:
![image](https://github.com/sainnhe/sonokai/assets/43652659/83e4538a-dc71-4101-bf32-ed6dadf370d4)

**Comment by antoineco** [comment]
That's probably because these two tokens have the same color in Sonokai (yellow). I agree that we should optimize in C/C++ files. 

Could you please:
1. Move your cursor over the word "Enter" inside the call to `printf()`, then call the Neovim command `:Inspect` and post the output?
2. Then do the same with your cursor over "%d".

**Comment by antoineco** [comment]
This is now fixed on `master`. Thanks for reporting!

**Comment by antoineco** [comment]
> Also, is it better to use white for brackets, commas, and semicolons in C/C++ files? They were originally white, but after using treesitter they became gray.

The Tree-sitter style (grey) is the intended one.
Unfortunately, we cannot achieve the same result in the Vim syntax because the [built-in c syntax](https://github.com/neovim/neovim/blob/9e436251de0329b1479365ff162d87ef18d6d14c/runtime/syntax/c.vim) defines `cParen`, `cBracket` and `cBlock` as _regions_, not as _matches_. Those regions are used to pinpoint imbalances between opening/blosing brackets, but cannot be used out of the box for highlighting punctuation.

For more context about why sainnhe made different design choices between the Vim and Tree-sitter syntaxes, please refer to https://github.com/sainnhe/everforest/issues/128.
