### ISSUE TITLE
Want parenthesis colored same as comments like vscode version

### ISSUE THREAD

**Issue by ronakg** [sainnhe/sonokai#3]
Hi,

I noticed that the VScode version has parenthesis colored the same as comments, but not the vim version.

Can you please do the same for the vim version?

**Comment by sainnhe** [comment]
This feature is currently technically impossible to achieve with a color scheme. The reason is simple: The syntax support in vim is very bad, many parentheses don't have highlight groups, which means they cannot be highlighted.

If you do need this feature, you can use plugin like rainbow parentheses to highlight them. You can customize a global variable of this plugin which controls the colors of parentheses, setting all the colors to grey should work

**Comment by ronakg** [comment]
Thanks for the clarification.

I added this in my `~/.vimrc` and that seems to do the trick.

```vim
augroup Parens
    autocmd! Syntax * :syntax match Parens /[\[\](){}]/
augroup END

hi def link Parens NonText
```

**Comment by sainnhe** [comment]
That's fine.
