### ISSUE TITLE
Is it possible to support KeitaNakamura/tex-conceal.vim?

### ISSUE THREAD

**Issue by YuCao16** [sainnhe/sonokai#53]
Expected behavior (github-theme):
<img width="311" alt="image" src="https://user-images.githubusercontent.com/62466929/161385946-4413b2ca-a838-4e88-985a-2dd2b51469cc.png">
Actual behavior (sonokai):
<img width="305" alt="image" src="https://user-images.githubusercontent.com/62466929/161385951-70d05927-aa47-4f21-b476-8da0d398530b.png">.
The current display is too blurry, is there any way to change the formula to white? 

($X_{t}=\int _{0}^{t}\mu _{s}\ \mathrm {d} s+\int _{0}^{t}\sigma _{s}\ \mathrm {d} B_{s}$)

**Comment by sainnhe** [comment]
The grey text is highlighted by `Conceal`, from `:h hl-Conceal`:

```text
							*hl-Conceal*
Conceal		placeholder characters substituted for concealed
		text (see 'conceallevel')
```

This hi group is used to control concealed symbols in vim, the best design for it is grey.

So I won't change this hi group, because if we do so, many designs will break.

If you don't care about the conceal feature, you can manually set this hi group to whatever color you like, see FAQ "How to use custom colors?"
