### ISSUE TITLE
Questions: Better way to highlight variable with {} in shell script

### ISSUE THREAD

**Issue by huyhoang8398** [sainnhe/sonokai#91]
![image](https://github.com/sainnhe/sonokai/assets/25379882/661f5238-1b55-444d-99b1-6408ae34cf97)

Is this possible to have a better highlight with treesitter for variable quoted by {} in shell script?

**Comment by antoineco** [comment]
I'm afraid not, because Tree-sitter applies a different capture group whether the variable is between brackets or not:

![image](https://github.com/sainnhe/sonokai/assets/3299086/54c215fa-0cbf-4ae8-9591-f8cec2e14fe3)

When the variable is not surrounded with brackets, the capture group is `@punctuation.special.bash`:

![image](https://github.com/sainnhe/sonokai/assets/3299086/71d42188-bd5f-4184-b96c-2cd553baf643)

However, when the variable _is_ surrounded with brackets, the capture group is  `@punctuation.bracket.bash`:

![image](https://github.com/sainnhe/sonokai/assets/3299086/659f4293-6679-4157-83cc-dce9d6ad8b7b)

That is something which can only be tackled in the Tree-sitter parser, not the colorscheme.
