### ISSUE TITLE
Question: Better highlighter command support for Dockerfile with treesitter

### ISSUE THREAD

**Issue by huyhoang8398** [sainnhe/sonokai#92]
![image](https://github.com/sainnhe/sonokai/assets/25379882/825f9948-7632-4368-8e76-6a4a8c69f150)

Is this possible to highlight these cmd for Dockerfile?
Bellow is an example with another colorscheme

![image](https://github.com/sainnhe/sonokai/assets/25379882/e3d518ba-7ab4-4f11-b1a5-612e338ef969)

**Comment by antoineco** [comment]
Yes, you simply need to enable Tree-sitter for the "Dockerfile" filetype with `:TSInstall dockerfile`.

Here is how it looks for me:

![image](https://github.com/sainnhe/sonokai/assets/3299086/4333f968-1776-4c49-a574-d24b47800acb)

**Comment by huyhoang8398** [comment]
<img width="1792" alt="Screenshot 2023-07-17 at 20 01 34" src="https://github.com/sainnhe/sonokai/assets/25379882/89659cd2-0e7b-4154-ad43-f5fadc9dbfcf">
It's strange, after i open nvim, i did see the highlight, but after 1 sec, it looks like this then

**Comment by huyhoang8398** [comment]
https://github.com/sainnhe/sonokai/assets/25379882/43638199-3401-4116-a792-50b256531ce3
You could see wget is highlighted, but then become white
<img width="1792" alt="Screenshot 2023-07-17 at 20 09 31" src="https://github.com/sainnhe/sonokai/assets/25379882/b2d4d69b-b355-4fbc-9f4f-5316e2f3cc0e">

**Comment by huyhoang8398** [comment]
https://github.com/sainnhe/sonokai/assets/25379882/1d6ebfed-ecf0-4a5d-9362-e75b3dfd4e68

Here is the video, you could see `wget` is highlighted as green and then becoming white

**Comment by antoineco** [comment]
Oh, you have the [LSP server for Dockerfile](https://github.com/rcjsuen/dockerfile-language-server-nodejs) active apparently, and that LSP server has [semantic tokens](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_semanticTokens) enabled. LSP semantic token are providing extra highlighting in addition to Tree-sitter.

Support for LSP semantic tokens was added in Sonokai in #86.

In https://github.com/sainnhe/everforest/issues/119, I tried to determine whether we could customize those color schemes ever further to improve the experience with LSP semantic tokens, but my conclusion was that LSP semantic tokens highlights sometimes conflict with Tree-sitter pretty badly. From my experience, this feature degrades the highlights more than it improves them. For instance, I wasn't able to enhance highlights for the Go language due to the priority that the LSP semantic token highlights were given over Tree-sitter's.

Thanks a lot for the video 👍 I will check whether we can improve the Dockerfile file type specifically for LSP semantic tokens. In case that's not possible, it's probably best to [disable that feature](https://gist.github.com/swarn/fb37d9eefe1bc616c2a7e476c0bc0316).

**Comment by antoineco** [comment]
I just investigated the issue, and unfortunately LSP semantic highlights override Tree-sitter entirely in this case.

Tree-sitter has smart queries which allows detecting and highlighting `sh`/`bash` inside Dockerfiles. You can see it in the screenshot below as:

```markdown
Treesitter
  - @variable.bash links to @variable bash    <!-- bash detected -->
  - @constant.bash links to @constant bash
```

Unfortunately, as soon as LSP semantic tokens are enabled, everything becomes a "parameter" instead, and the embedded highlights are overridden:

```markdown
Semantic Tokens
  - @lsp.type.parameter.dockerfile links to @parameter priority: 125  <!-- higher priority than Tree-sitter -->
```

Screenshot:

![image](https://github.com/sainnhe/sonokai/assets/3299086/1f347b3c-2776-4e50-bfb6-9ae9d5a11ea6)

That's why all the colors disappear in your video. I see the exact same behavior in my Neovim with the `dockerls` LSP server enabled.

---

I was able to disable this feature in `dockerls` with the following lspconfig:

```lua
local lspconfig = require "lspconfig"

lspconfig.dockerls.setup {
  on_attach = function(client, bufnr)
    client.server_capabilities.semanticTokensProvider = nil
  end,
}
```

![image](https://github.com/sainnhe/sonokai/assets/3299086/32471377-0c3e-4010-b97b-cda9a2815f34)

**Comment by huyhoang8398** [comment]
<img width="1792" alt="Screenshot 2023-07-17 at 23 42 32" src="https://github.com/sainnhe/sonokai/assets/25379882/2fd8bbaf-1508-4e17-b358-8512630518a4">

> I was able to disable this feature in dockerls with the following lspconfig:

After disable tthat feature, it's working well now, thanks
