### ISSUE TITLE
Variables starting with uppercase letter have different color

### ISSUE THREAD

**Issue by CharlieCheckpt** [sainnhe/sonokai#94]
Hello,

Thank you for this very nice color theme.

In python, variables starting with an uppercase letter have a different color, which I found quite misleading : 
<img width="204" alt="image" src="https://github.com/sainnhe/sonokai/assets/10373261/eb00a2ae-3032-490c-99c2-64d6d45263ce">
I'd like `myvar` and `Myvar` to both be white.

I don't know if this is a bug or an intended behaviour, or even if it has to do with `sonokai` (`treesitter` maybe ?).
Do you know what causes this difference of color, and if there is any way to fix it in sonokai?

Thanks !

**Comment by antoineco** [comment]
Possibly Tree-sitter, but most likely LSP semantic highlights.

Could you please share the output(s) of `:Inspect` while hovering both symbols?

**Comment by antoineco** [comment]
In Python uppercase names are often used for classes, so I assume that Tree-sitter treats all uppercase variables as types.

Using a LSP server with semantic highlights should fix that. It works in combination with Tree-sitter but provides more accurate context.

Otherwise, you can override the highlight for Python types in your `init.lua` file, with the side effect that actual Python types will be highlighted like variables:

```lua
-- Apply custom highlights on colorscheme change.
-- Must be declared before executing ':colorscheme'.
local grpid = vim.api.nvim_create_augroup('custom_highlights_sonokai', {})
vim.api.nvim_create_autocmd('ColorScheme', {
  group = grpid,
  pattern = 'sonokai',
  callback = function()
    local config = vim.fn['sonokai#get_configuration']()
    local palette = vim.fn['sonokai#get_palette'](config.style, config.colors_override)
    local set_hl = vim.fn['sonokai#highlight']

    set_hl('@type.python', palette.fg, palette.none)
  end
})
```
